### ISSUE TITLE
[메인화면] 상단바 및 메인 피드화면 구현

### ISSUE THREAD

**Issue by devmhl** [aeuna/sullivan-SNS#3]
### 화면 구성
1) 상단바
- 공통 레이아웃으로 고정
- ‘+’ 버튼 클릭시 게시물 업로드 화면으로 이동
- 프로필 버튼 클릭시 내 피드로 이동
- 알림 버튼 클릭시 알림 확인 (드롭다운메뉴)
2) 게시글 영역 
- 게시자 프로필사진, 아이디 표시
- 게시물 사진
- 하트아이콘 클릭시 하트 +1 (애니메이션 효과 귀여운거)
- 댓글아이콘 클릭시 댓글 작성 폼 나타남.
- 기본적으로 댓글 3개 보여줌. (아이디, 댓글내용만 표시)
- 게시물은 3줄 이상 넘어가면 ‘더보기’로 줄여서 표시
- 더보기 누르면 디테일 페이지로 가도록!
- 화면은 무한스크롤 구현

**Comment by kelee98** [comment]
#3 상단바 로그인시 회원 이름 뜨도록 변경

**Comment by aeuna** [comment]
1. 오늘 계획했던 일정
 - feed DB에서 가져와서 feed컴포넌트에 적용시켜보기
2. 실제 작업한 내용
- api 따로 폴더 파서 진행 및 DB 데이터값 가져와서 뿌려주는것까지 진행
3. 딜레이된 부분
- DB날짜가 타임스탬프로 찍혀 포맷 변경해야함 
- 하트누르면 하트 수 업데이트되는 api필요
- 사진 url 부분들 
4. 피드백 받은 코드리뷰 반영 여부
- 아직 받지 않음!
5. 내일 작업 계획
- 6월 9일 오후 9시30분에 시험 마감이 있어 그 이후에 상황에 따라 진행할 예정!

**Comment by aeuna** [comment]
1. 오늘 계획했던 일정
 - feed DB api 로 빼지 않고 파일 내에서 해결
 - date format
 - 하트 누르면 하트 수 업데이트 되는 작업 수행
2. 실제 작업한 내용
- 윗 부분 작업
3. 딜레이된 부분
- 유저가 좋아요 했는 지 여부 필요

- 하트 누르면 하트 수 업데이트 되는 부분 => 어떤건 작동이 되고 안되고 했는데 확인 필요함 
- 피드 생성 uid, like 생성되어야 함
=> 피드생성될때 uid 추가 되니까 잘됨

4. 피드백 받은 코드리뷰 반영 여부
- 아직 받지 않음!
5. 내일 작업 계획
- 딜레이 된 부분 해볼 예정!

**Comment by huiji0315** [comment]
### 21.06.13 리뷰
**=> 06.14 작업 by euna** 

**2. 게시글 영역**
- [X]  피드 자체에서는 좋아요 수가 1로 올라가지만 새로고침하면 저장되지 않음 => feed에 uid가 올라와 있지 않은 경우 제외하고 작동확인 완료!
- [X] 게시물은 3줄 이상 넘어가면 ‘더보기’로 줄여서 표시 => content 내용이 180자 넘어가면 샬라샬라... 이런식으로 표현되도록 함!
-> 3줄 이상 넘어가지 않아도 항상 더보기가 있음 => 이거는 있어야  될듯! 디테일 페이지로 들어갈수있는 유일한 수단!
- [X] 더보기 누르면 디테일 페이지로 가도록!
- [X] 장소 태그는 메인 피드에서 보이지 않음 => cardHeader에서 표시!
- [X]  게시글을 올린 순서대로 올라오지 않고 뒤죽박죽으로 올라옴 => create_at 으로 최신순으로 정렬 완료!
- [X] 메인피드 사진부분에 마우스를 올리면 나오는 설명이 모두 food로 되어있음
- [X] 게시글 내용과 태그한 사람이 바로 위아래로 붙어있어서 구분이 필요할 것으로 보임(위치 혹은 색깔, 표식 등...?) => 미현언니가 해결
- [X]  게시글 업로드 시에 사진을 올리지 않아도 사진과 같은 크기로 빈 상자가 올라오고, 마찬가지로 해당 부분에 마우스를 올리면 나오는 설명이 food로 나옴 

+)
앞으로 해야할것
- 어떤 유저가 좋아요 했는지 여부도 알 수 없음
- 댓글을 작성해도 새로고침하면 저장되지 않음
- 기본적으로 댓글 3개 보여줌. (아이디, 댓글내용만 표시)
- 하트아이콘 클릭시 하트 +1 (애니메이션 효과 귀여운거)
- error 처리
![스크린샷 2021-06-14 오후 3 58 32](https://user-images.githubusercontent.com/42725903/121852154-04eea000-cd2a-11eb-94be-f4d95ff5ae6a.png)

**Comment by devmhl** [comment]
### 수정사항
- 태그 아이콘 마우스 호버시 태그 내용이 툴팁으로 표시되도록 수정함

**Comment by devmhl** [comment]
에러사항 수정 확인
