### ISSUE TITLE
[상세화면] 게시물 디테일 화면 구현

### ISSUE THREAD

**Issue by devmhl** [aeuna/sullivan-SNS#4]
### 화면 구성
- 팝업이 아닌 전체화면으로 구성
1) 게시물 영역
- 사진 더 크게 보여줌
- 게시물 펼쳐서 전체글 보여줌
2) 수정 및 삭제버튼
- 작성자일 경우에 표시
- 수정버튼 클릭시 수정화면으로 이동
- 삭제버튼은 삭제확인 모달창 띄워준 뒤 삭제처리
3) 우측 사용자 프로필 영역
- 현재 로그인된 사용자 정보 간략하게 띄워줌
4) 댓글창
- 사용자프로필사진/댓글내용보여주기
- 수정/삭제는 구현하지 않음

**Comment by huiji0315** [comment]
### 21.06.13 리뷰

- 메인 피드에서 특정 게시글을 클릭하면 아직 디테일 페이지로 연결되지 않음
- "http://localhost:3000/feed/[id]" 을 통해 들어가서 볼 수 있음
- 오른쪽에 댓글 올라온 것들이 보이는데, 추가로 댓글을 입력해도 반영되지않음
- 댓글 창이 크게 넓혀지지 않고 오른쪽 여백이 너무 많음
- 디테일 페이지 자체에서는 좋아요 개수가 보이지 않음(아마 좋아요 갯수의 연동이 안되는 것으로 생각됨)
- 게시글 더보기를 누르면 메인페이지로 이동해버림

**Comment by aeuna** [comment]
하트 업데이트 부분 수정

**Comment by devmhl** [comment]
디테일 화면 에러사항 수정 확인
