### ISSUE TITLE
[교육자료] 피드백

### ISSUE THREAD

**Issue by devmhl** [aeuna/sullivan-SNS#45]
## 기간
- 피드백 진행 : 6/30 수요일까지
- 피드백 반영하여 수정된 자료 업로드 : 7/2 금요일까지

## 할 일
1. 공유문서함에 업로드된 모든 교육자료를 읽어본다.
2. 코멘트에 해당 문서 @작성자를 언급해서 피드백 남기기
```
- 이해하기 어려운 부분
- 더 추가했으면 하는 내용
- 글 형식 : 너무 긴 글, 부적절한 말투, 복잡한 문단 구조 -> 어떻게 바꾸는게 좋을지 제안과 함께 작성하기
```

**Comment by huiji0315** [comment]
### [API_guide_create] 피드백 @xianeml 
**(p.5)** 
- 파일을 저장하는 비동기 처리가 끝나면~
: 비동기 처리가 무엇인지 간단한 설명이라도 해줘야 하지 않을까?
이해하지 못하는 사람들이 있을 수 있을 것으로 생각됨.

**(p.7)**
- createParams에 중괄호가 있는걸 보니 분명 내용은 객체일텐데~
: 중괄호가 있으면 객체여야한다는 것을 인지하지 못할 수도 있지 않을까?
javascript로 웹페이지를 만들어본 학생들을 모집한다고 해도
문법적인 개념에 대해서 인지하지 못하는 학생들이 있을 것으로 생각됨.
이를 위해서는 '객체일텐데'라는 말보다는
변수에 중괄호를 할당한다는 개념이 객체이고, 객체는 key, value의 형태로 이루어져있다.
와 같은 투로 바꾸면 좋지 않을까라는 생각이 들었음.

**Comment by huiji0315** [comment]
### [guide_form] 피드백 @aeuna 
**전반적인 사항**
 - 해주었답니다. 해줄거랍니다. 보다는 해주었어요. 해줄거예요. 등의 말투로 통일하는게 낫지 않을까?

**(p.1)**
- 폼 이미지 바로 아래 문단 botton 오타 -> button
- form id는 button 요소가 포함될 form 요소를 알려준것이예요.
: 요소라는 말이 들어가서 더 이해가 어려운가? 정확히 와닿지 않는 느낌?
더 쉽게 설명해준다면 좋을 것 같음.

**(p.2)**
- '사진 파일 첨부' 문구 모두 색깔 변경을 하는 것이 맞지 않나?

**(p.3)**
- 맨 윗줄: 사진 url, ~ 값를 오타 -> 값을

**<---**
앞에서 form 태그가 무엇일까? 와 같이
<<폼의 속성, 함수 살펴보기>> 등의 제목으로 한번 나눠주기
**--->**

**(p.4)**
- 여기서 크게 살펴볼 속성들인 오타 -> 속성들은
- value 설명 문단에서 되어있어요. 우리가~ -> 사이에 띄어쓰기!
- onChange 이벤트를 사용해서, 이벤트가 발생하면 -> onChange 이벤트가 발생하면
- e를 받아오면, setContent(e.target.value)를 통해, -> 그리고 setConent(e.target.value)를 통해,

**(p.5)**
- 피드를 생성하면, user의 생성한 피드 uid를 가지고 있는 -> 피드를 생성하면, user가 생성한 피드의 uid를 가지고 있는
- 기존에 ~ -> 앞에 '그러면, '을 붙이면 더 좋지 않을까?
- 값을 가져오는데 시간이 걸리기 때문에 비동기 처리를 해주었답니다.
: 시간이 걸리는데 왜 비동기 처리를 해줘야 되는지 추가 설명이 있다면 좋을 듯?
- updateUserFeedList(), createFeed() -> 볼드체 등으로 눈에 띄게 해주는 것이 좋을 듯?
- updateUserFeedList() 함수 코드 블럭이 너무 커서 아래 설명과 비교하면서 찾아보기 힘드므로, 
'기존에 user가 가지고 있는 feedList를 가져와야겠죠?' 부분과 '어떻게 feedList에 지금 내가 생성하는 피드 id를 추가해줄까요? (newFeedList)' 부분의 코드 블록을 나누는게 좋지 않을까?

**(p.6)**
- newFeedList와 userDocsRef 를 사용해, 우리는 update를 해줄거니까 -> userDocsRef에 newFeedList를 update 해줄거니까
- createFeed의 코드 블럭 내용과 [API_guide_create] 자료에서 '3. create API 작성' 부분의 코드 블럭 내용이 충돌하는 것으로 보임.
-> 최신 코드 블럭 상태로 통일해주어야함.
-> [API_guide_create]과 [guide_form] 에서 createFeed 부분의 설명을 어디에서 하면 좋을지 논의가 필요함. 
아니면 둘다 포함시킬 것인지.

**Comment by huiji0315** [comment]
### [API_guide_update] 피드백 @xianeml 
**(p.2)** 
- 데이터를 받아와야 다음 과정을 수행할 수 있도록 정상적인 수행 절차를 만들어주는 것이지요. 
-> 데이터를 받아와야 다음 과정을 정상적인 절차로 수행할 수 있기 때문이지요.
- 상세피드 문서까지의 경로를 참조할 수 있도록 feed 문서 레퍼런스라는 의미의 feedRef 변수에 담았어요! 
-> 상세피드 문서까지의 경로를 참조할 수 있도록 해당 경로를(=목적어 삽입) feed 문서~ 

**(p.3)**
- 데이터를feedDetail ~ -> 띄어쓰기
- '상태' 라는 글씨가 오히려 안보임(빨간 글씨 부분) -> 통일해서 볼드체로 바꾸는게 낫지 않을까?

**Comment by huiji0315** [comment]
### [API_guide_delete] 피드백 @xianeml
- 눈에 띄는 수정사항은 없는 듯함.

**Comment by huiji0315** [comment]
### [API_guide_read] 피드백 @aeuna 
**전반적인 사항**
- **[guide_form]** 과 더불어 **[API_guide_read]** 도 다른 guide와 같이 
번호를 붙여서 문단을 눈에 띄게 구분해준다면 가독성이 더 높아져 좋을 것 같음.
- 또한, 중요 단어나 함수에 볼드체 등의 처리를 해준다면 더욱 보기에 편할 것 같음.

**(p.1)** 
- useState를 사용해서 feeds와 loading 상태인지를 관리할거에요.
: feeds 상태가 무슨 상태인지 설명이 필요할듯?

**(p.2)**
- async function getPhotoUrl()과 같이 async 문법을 통일하기로 했었는데,
코드 상에서 fetchData() 함수만 .get().then().catch() 등의 형식으로 되어있음.
: 이 함수만 이렇게 의도적으로 처리한건지?

**Comment by devmhl** [comment]
# 이론 자료 - [웹의 동작 방식] 피드백
@huiji0315 

- **MDN 문서를 그대로 교육자료로 제공하기 보다는 교육자가 이해하기 쉽고 흥미를 가질 수 있도록 내용을 재구성하는 게 좋을 것 같음**
### 번역어 문체 수정하기

- `이것은, 그것은, 그들은` 등 대명사 삭제
- 피동형 말투 삭제
:영문체를 번역한 것처럼 딱딱한 느낌을 줘서 잘 읽히지 않음
- 흥미를 끌고 쉽고 빠르게 읽기 위해 간결한 능동형 문장 사용하길 추천


## 1p)
### 오타, 문장 수정
- 첫 문장을 더 간결하게 작성하면 좋을 것 같음.
 => "웹에는 클라이언트와 서버라는 컴퓨터가 연결되어 있습니다. 두 컴퓨터가 상호작용하는 방식은 다음 그림과 같습니다. "

- 클라이언트의 장비가~ -> '장치'로 오타 수정


### 도로 이미지로 비유
- 이 부분부터 중제목 붙여주기. '웹이 도로라고 상상해 봅시다' 를 중제목으로 하는건 어떨지? 
- 비유를 활용해서 더 상세한 예시를 덧붙이면 좋을 것 같음.
: 클라이언트를 집으로, 서버를 음식점으로 비유하고, 배달 앱을 통해서 배달을 요청하면 음식점은 음식을 준비해서 응답한다. 등


## 2p) 
- 인터넷 연결에 대한 비유는 `우리집과 상점을 연결해주는 배달앱` 또는 `집과 상점을 이어주는 도로` 라고 수정하면 좋을거같음
- `제안` : 각 개념 설명 영역마다 소제목을 달아주면 더 이해하기 편함
: 인터넷 연결 영역엔 '상품을 주고받아요' 라고 소제목 붙이고,
HTTP 영역엔 '주문서를 보내요' 등 우리 커리큘럼 소제목 작성했던 것처럼 쉽고 짧은 비유로 소제목을 작성하면 어떨까?

### HTTP
- HTTP 문단을 DNS 위로 올리는게 흐름상 이해하기 좋을 거같음
- 통신할 수 있게 하기 위한 -> 통신하기 위한 
- 상품을 주문하기 위해 여러분이 사용하는 언어와 같습니다
: 이 언어가 한국어를 말하는건지 주문내역을 말하는 건지 이해하기 어려울 수 있음
=> 상품을 주문하기 위해 주문 양식에 따라 주문서를 보내는 것과 같습니다 등으로 구체화하기

### DNS
- ( 아래를 보세요)는 어떤 영역을 가리키는 건지?
- 이것은 여러분이 접근하기 위해 상점의 주소를 찾아보는 것과 같습니다.
=> `상점에 가기 위해` 또는 `먹고싶은 음식을 고르기 위해 배달 가능한 상점 목록을 뒤져보는 것과 같습니다.`

### 컴포넌트 파일
- 소제목을 '메뉴는 어떻게 구성되어 있을까요?' 등으로 적으면 좋을거같음
- 코드파일에서 `다른 기술들도 잠시 뒤 보게 되실것이지만,`은 문맥상 필요없는 내용이라 삭제
- 자원에서 `웹사이트를 만드는 모든 다른 것들을 위한 공동적인 이름입니다.` -> 웹사이트를 만드는 모든 구성요소를 의미합니다.로 수정


자료 직접 수정 예정

**Comment by devmhl** [comment]
# 이론 자료 - [API] 피드백
@huiji0315 

- 위와같이 서치한 문서를 그대로 제공하지 않고 교육자가 이해하기 쉽도록 재구성해주기

**Comment by devmhl** [comment]
# 실습 자료 - [form_guide] 피드백
@aeuna 

## 1p)

게시물을 업로드는 데이터를 서버에 전송하여 데이터베이스에 저장하는 작업입니다.

## 2p)

- 피드를 생성하기 위해서는 생성하기 위한 form 이 필요합니다 → 데이터베이스에 전송하기 위한 양식이 필요합니다.

## 3p)

- 첫줄 오타 : 태그의 값를  → 값을로 변경
- useState를 사용하여 선언을 해주었답니다 → ~사용하여 `상태를` 선언해주었답니다.
- useState에 대한 간략한 설명 추가 필요

    ```jsx
    const [ 상태, 상태를 변경하는 함수 ] = 리액트.useState(상태 초기값)
    ```

- form id는 edit이고~ `핸들러라고 생각하면 됩니다`. → `핸들러 함수입니다.`

## 4p)

- 크게 살펴볼 속성으로 언급한 부분에 하이라이트로 강조하기
- value는 입력태그의 초기값을 말하며 → 입력된 값을 말하며
- 우리가 위에서 content 의 초기값을 → content 상태 변수의 초기값을
- type이 submit인 공유 버튼을 누르면 form의 onSubmit 이벤트가 발생해요.

⇒  우리가 작성한 양식이 서버로 전송되는 onSubmit 이벤트가 발생해요!

- 이벤트가 발생하면 → 양식이 전송되면

 

## 5p)

- `user의` 생성한 피드 uid를 ~ → `사용자가` 생성한 피드 uid를~
- 마지막 문단 : user 데이터 중 우리는 `feedList가` 필요~ → user 데이터 중 우리는 `feedList 필드만` 필요~

## 6p)

- 기존에 feedList가 없다면 새로운 피드 리스트를 만들어줘야 하기 때문에, 배열에 {feedId: uid} 객체 하나를 추가합니다.
- `userDocRef.update({...}) 이렇게` 업데이트 해줍니다 → `feedList 필드값을 우리가 만든 새로운 feedList 배열로` 업데이트 해줍니다.

    ⇒ 이 함수가 어떤 동작을 하려는지 좀 더 풀어서 설명해주면 좋을 것 같음.

- `피드를 생성`하기 위한 마지막 작업이랍니다 → 이제 `파이어스토어 피드 컬렉션에 새로운 피드 문서를 생성하기 위한 함수를 작성`해봅시다.

     ⇒ createFeed 함수는 데이터베이스에 추가하기 위한 역할을 하기 때문에 풀어서 설명해줌

- author는 `user 나의` 정보를 → `user 컬렉션에 있는 내` 정보를
- `like는` 초기값 0 → `like는 좋아요 수를 의미하며` 초기값 0~

**Comment by devmhl** [comment]
# 실습 자료 - [API_guide_read] 피드백
@aeuna

## 1p)
![image](https://user-images.githubusercontent.com/67747870/124360210-88354e80-dc63-11eb-9217-57db5df13d48.png)


## 2p)
![image](https://user-images.githubusercontent.com/67747870/124360218-92efe380-dc63-11eb-8dea-376cac73f7cb.png)

## 3p)
![image](https://user-images.githubusercontent.com/67747870/124360235-a26f2c80-dc63-11eb-977a-3e22ac073ce8.png)
![image](https://user-images.githubusercontent.com/67747870/124360246-ae5aee80-dc63-11eb-8ca7-71ad73ccb41c.png)

## 4p)
![image](https://user-images.githubusercontent.com/67747870/124360253-b61a9300-dc63-11eb-9f7d-829db17b7424.png)


알아볼 수 없는 글씨는 다시 코멘트 작성할게...❤️

**Comment by aeuna** [comment]
### create API 사용 가이드

@xianeml 
p.4
1. 첨부파일 url 가져오기
=>  getPhotoUrl 함수를 통해서파이어스토에 저장한다음에 그 링크를 가져오는데 사진을 공유하기 누르기 전에 또 다른 사진으로 바꾸면 그것도 올라가는지? 이것을 방지하는게 필요할것 같음! 아니면 파이어스토어에 올리지 않고, 이미지 미리보기를 구현하거나!

p.7 
1. key 와 value를 함쳐서 표현할수 있다는것 ->  비구조화할당 문법이라는것을 언급하면 좋을까??
2. set(). => .set() or set() 오타있음!

**Comment by aeuna** [comment]
### delete API 가이드

@xianeml 
p.1
1. delete(). => .delete() or delete() 오타 있음!

**Comment by aeuna** [comment]
### update API 가이드

@xianeml 
p.1
1. useRouter에 대한 참고자료도 있으면 좋을듯.
2. 자바스크립트의 구조분해 할당 문법을 사용하면 리턴된 객체의 밸류값을 키 이름의 변
수로 바로 사용할 수 있습니다. => 위에서도 value 라고 했으니, 밸류값을 영어로 value로 통일 시키면 좋을듯.

p.2
1. 자바스크립트의 async awiat 문법을 사용합니다. => await 오타 있음!
2. .get(). => .get() or get() 오타있음!

p.3 
1. 피드 데이터를feedDetail 변수에 => 피드 데이터를 feedDetail 변수에 (띄어쓰기)

p.4 
1. 익명의 이벤트 핸들러가 무엇인지 써주면 좋을것 같음. 사실 이 수식어를 처음 들어봄! 익명의 ~~

**Comment by aeuna** [comment]
### 웹의 동작 방식
@huiji0315 

p.1
1. 클라이언트 예시를 든것은 좋은데, 그 예시에서 클라이언트가 무엇인가가 명시되어있으면 좋을것 같음.
2. 클라이언트와 서버의 소통방식에 대한 사진 자료가 더 있으면 좋을것 같음. 위의 요청과 응답을 주고 받으면서 상호작용을 한다는 설명을 보충하는 이미지가 있는것 처럼!

p.2 ~ p.4 윗절까지 비유 설명 매우 좋은것 같음!

p.4 
1. 프로토콜이 계층화 되어야 한다는 개념을 강조 한것 같은데, 이 부분을 좀 더 쉽게 풀어 써주면 좋을것 같음. 네트워크, 프로토콜 이런 용어를 처음 접하는 사람이라면 이해하기 약간 어려울수도 있을것이라고 생각함.

**Comment by aeuna** [comment]
### API
@huiji0315 

p.1
1. Human User Interface 와 달리 라고 했는데, Human User Interface 이 용어를 처음 접하는 사람들도 있을것 같아서, 서드 파티 처럼 용어정리를 해주면 좋을듯!

p.2 
1. API의 또다른 예시에 대해서 살펴볼까요? => 또다른을 빼도 될듯. 위에서는 응답메시지 형태에 대해서만 이야기를 했으므로

**Comment by devmhl** [comment]
# 이론 자료 - [웹의 동작방식(최종)] 피드백
@huiji0315 

너무 완벽합니다... 얼른 교육서로 출판해야합니다... 
각 설명마다 비유가 있어서 이해하기 좋았음 👍👍👍
