### ISSUE TITLE
[마이피드] 내가 올린 게시물 페이지 구현

### ISSUE THREAD

**Issue by devmhl** [aeuna/sullivan-SNS#5]
### 화면 구성
1) 프로필 영역
- 프로필 사진, 사용자 정보 표시
- 프로필 수정 팝업을 통해 사용자 정보 업데이트 가능
2) 게시물 영역
- 내가 올린 게시물들을 이미지 그리드로 확인 가능
- 사진 클릭 시 게시글 디테일 페이지로 이동

**Comment by devmhl** [comment]
1. 작업내용 : 마이피드 css 스타일 전체 수정
2. 다음 계획 : 
- 사진 피드 paper 컴포넌트 사이즈 정방형으로 고정시키기
- 이미지 추가 시 react image 컴포넌트 사용
- 프로필 수정하기 팝업 추가
- api 연동

**Comment by huiji0315** [comment]
### 21.06.13 리뷰

- 공유 버튼 클릭 후 마이피드 페이지로 넘어오는데, 이 자체에서 게시물 올린 것을 바로 볼 수는 없음 (게시물 영역 아직 구현 안됨)
- 수동적으로 main 페이지로 넘어오면 업로드된 게시물 확인 가능

**Comment by aeuna** [comment]
1. 좋아하는 피드 수 표시 
2. 게시글이 바로 안뜨는 현상 수정 => user.uid가 처음에 undefined가 떠서 제대로 query가 안들어갔던것 같음

**Comment by devmhl** [comment]
에러사항 수정 확인
