### ISSUE TITLE
[코드리뷰] 최종 코드리뷰

### ISSUE THREAD

**Issue by devmhl** [aeuna/sullivan-SNS#52]
- 코드베이스 수정 기한 : 7월 20일 화요일
- 최종 코드 리뷰 일정 : 7월 21일 수 ~ 22일 목

### 리뷰 방법
- 범위 : components 폴더부터 pages 폴더까지 모든 코드 살펴보기
- 피드백이 필요한 파일 이름과 피드백 내용을 코멘로 남기기
- 어떻게 개선하는게 좋을지 제안도 구체적으로 남겨주기!

### 살펴볼 내용
1. 변수명/함수명을 보자마자 무슨 의미이고 어떤 동작을 수행하는지 이해할 수 있나요?
2. 코드 위치가 다른 파일들이랑 통일되어 있나요?
3. 보자마자 눈이 아프고 이해가 안되는 부분은 @언급 해서 설명 요청해주세요.
4. 스타일이나 컴포넌트에 사용하지 않는 변수가 있나요?
5. 더 이해하기 쉽게 작성하는 방법을 알고있나요?

**Comment by devmhl** [comment]
## components 폴더
### /common/Snackbar
- [x] 2~5라인 material ui import 한줄정리 필요
- [x] 12라인 함수는 컨벤션에 맞게 useEffect() 아래로 옮기기
### /edit/UploadForm
- [x] 35라인 photoUrl은 생성/수정 시 넘겨주는 데이터이기 때문에 아래 상태들과 같이 붙여주기
- [ ] 62라인 getPhotoUrl() 함수는 API에 작성하기
- [x] 62라인 api 사용시 try~catch 에러 핸들링 추가
- [ ] 105라인 피드 생성 시 필요한 uid도 화면에서 보내지 말고 API에서 처리해주기
### /edit/PhotoPreview
- [x] 60라인 file input 필요 없어보이는데 사용되는 건지 확인 필요
### /feed/Comment
- [x] 30라인 inputs 상태 초기값에 객체 말고 빈 스트링으로 수정('')
- 객체 사용할 필요없이 33라인 `handleTextChange()`함수를 통해 e.target.value를 세팅하면 코드가 더 간단해짐
- [x] 54라인,63라인 스타일은 상단 makeStyles에 정의하기
- [x] 42라인 comment 객체에 user.photoUrl을 추가하고 CommentDetail 컴포넌트 11라인 아바타에 photoUrl값 할당해주면 댓글등록시 사용자 프로필사진 노출 가능
### /feed/CommentDetail
- [x] photoUrl 프랍스로 받아서 11라인 아바타 속성값에 추가하기
### /feed/Feed
- [x] 48라인 expanded 변수명이 뭘 확장하려는건지 분명하지 않아요. commentExpanded등으로 변경하면 좋을것같음
- [x] 72라인 handleExpandClick 함수명도 handleExpandComment 로 수정
- [x] `checkFeed = [...user.likeFeeds];`은 불필요.  윗라인 `setLikeFeeds(user.likeFeeds);`를 통해 user.likeFeeds로 상태를 업뎃해줬기 때문에 그 상태를 사용하면됨!
- [x] 83라인 ` if (feedId === uid)` 을 보면 uid가 어떤 uid인지 명확하지 않음. 한번 더 위로 올라가서 55라인의 구조분해 문장을 살펴보게 됨. 그래서 차라리 구조분해 안하고 `feed.uid`라고 명시하면 바로 문장을 이해하기 쉽지 않을까?
- [x] 위와같은 이유로 55라인 구조분해 문장이 불필요한것같음
- [x] 70라인 liked 상태명을 likeBtn으로 명확하게 명시하면 어떨지. 상태가 갖고있는 객체를 보면 71라인 status 변수명은 한번에 이해하기 어려운 것 같음. `likeBtn.clicked`는 어떨지? num은 더 구체적으로 `displayNum` 어떤지?

**Comment by aeuna** [comment]
### pages/index.js , pages/[feedUid].js

- [x] 1. [feedUid].js 에서는 getServerSideProps로 use정보와 feed 정보를 가져오고, index.js 에서는 사용하지 않는데 이부분 통일이 필요.
- [x] 2.  await fetchUserInfo.json(); 이부분 변수명 통일 필요 ( userInfo vs user ) => **userInfo**를 쓰는게 나을듯 / 다른 컴포넌트에서 userInfo를 사용하고 있어서!
- [x] 3.  api 불러올때, fetch부분에서 어는 부분은 앞에 localhost 가 붙고 안붙는데 이부분도 통일 필요.

### pages/_app.js

- [x] 1. 주석 지워도 되는지?

### pages/404.js
- [x] 1. 어느 페이지에서 사용하고 있는지? => 일단 그대로 두고, 설명할때 잘못된 url로 이동시 해야된다는것을 알려주기!!


### components/Feed.jsx

- [x] 1. **36번 비구조화문법**을  useStyles()와 useState()아래로 옮기는게 나을지?
- [ ] 2. api에서 method, body. Header 개념설명하는지 우리 드라이브 확인해 봐야겠다.

### components/DetailFeed.jsx

- [x] 1. **55번 비구조화문법**을  useStyles()와 useState()아래로 옮기는게 나을지?
- [x] 2. makeStyles 에서 **deleteText** 사용안하고 있음

### components/PopperMenu.jsx

- [x] 1. makeStyles에서 **theme** 사용안하고 있음


### components/edit/UploadForm.jsx

- [ ] 1. 지금 약간 phodoUrl, content, location, tag, author 요소들을 다 각각의 state로 관리하고 있는데 const initialState = { photoUrl : “”, content: “”, location: “”, tag:””, author: {}} const [ state,  setState] = useState(initialState); 하나로 통째로 관리하는건 어떨까?
- [ ] 2. getPhotoUrl에서 이미지 미리보기 링크 구현할때, 사진을 바꿀때마다 파이어베이스 스토리지에 올리고 구현되는건 비효율적인것 같음!  onChange 될때 **파일객체랑 onloadend** 사용하면 구현 가능. 간단하게 적어보면 let reader = new FileReader(); let file = e.target.files[0]; reader.onloadend = () => { … setSteate(file: file, previewUrl : reader.result } reader.readAsDataUrl(file); 요런식으로 찾아보면 스토리지에 올리지 않아도 previewUrl 통해 미리보기 구현 가능

### components/edit/photoPreview.jsx

- [x] 1. makeStyles에서 **theme** 사용안하고 있음

### components/myfeed/profileUpdatePopup

- [ ] 1. uploadForm 1번 과 같이 form 입력 데이터 상태를 **하나의 state**로 관리하는게 어떨지?

### firestores

- [x] 1. firebaseconfig.js 와 firebase.js **한 파일**로 합치는건 어떤지?
- [x] 2. api Key 같은것들 **.env** 파일로 빼는게 어떨지?

### Api

- [x] 1. const db = firebase.firestore()를 각 파일에서 계속 선언하고 있는데 firesotres에서 firebase.js에서 **export const db= firebase.firestore()** 이런식으로 쓰는건 어떤지?

### Myfeed 

- [x] 페이지에서 큰 화면으로 보면 디자인이 괜찮은데, 노트북으로 보면 피드가 한줄로 붙어서 나옴.

**Comment by huiji0315** [comment]
## components 폴더
### edit/PhotoPreview.jsx
- [x] '사진을 업로드 하세요.' 글씨 크기를 줄여서 한줄에 보이도록 하는 것이 좋을듯

### edit/SubmitButton.jsx
- [x] 20라인 : router.push()와
feed/Feed.jsx 131라인 : window.location.href = `/feed/${uid}`; 의 차이가 뭔가요?

### feed/Comment.jsx
- [x] 댓글 입력해서 send 버튼 누르면 댓글창에 올라가는데
댓글창을 닫았다가 다시 열거나 디테일 페이지에 가보거나 등을 하면
상태가 유지되지 않는 이유에 대해서 설명해주면 좋을듯
ex) 코드 상으로 setInputs하고 setComments했는데 왜 유지되지않는지?

### feed/DetailFeed.jsx
- [x] 82~90라인 : 좋아하는 피드들 전체를 살펴보면서 feedid가 uid와 같으면
like 상태로 만들어주고 반복을 멈추는데 이 부분이 정확하게 무엇을 구현한건지 한번에 파악하기 힘듦
- [x] 93라인 : handleHeartClick() 함수 구현도 feedId와 uid를 비교해서 update하는 것 같은데 자세한 설명 부탁드립니다.
- [x] 151라인 : 실습 설명때 조건부렌더링연산자(&&) 설명해줘야할듯

### feed/Feed.jsx
- [x] 55~70라인 : 위에 언급한 feed/DetailFeed.jsx의 '82 ~ 90라인'과 비교하면서 설명해주면 좋을듯
- [ ] fetch api 부분은 어디에서 어떤 방식으로 가져와서 뭘하려고 하는건지에 대해서도 자세한 설명을 해주면 좋을 것 같습니다.(개념 설명 필요)
다른 fetch들과 비교해가면서 설명해주면 이해가 더 쉬울 것 같음
- [x] Feed 컴포넌트 이름을 MainFeed로 하면 어떨지?

### layout/NotificationBar.jsx
- [x] 원래 Bar라고 하는지?
Header 컴포넌트 이름에 Bar의 느낌이 포함되어있어서
NotificationBar보다는 NotificiationMenu 등으로 바꾸면 어떨지?

### myfeed/PhtoGrid.jsx
- [x] 은아 말처럼 피드가 한줄로 붙어서 보임
그리고, 사진이 위아래로 늘려서 길쭉하게 보임(정상보다 세로로 늘린 느낌)

### myfeed/PhotoItem.jsx
- [x] 32라인 : Link href를 사용한거는 또 앞에서
router.push()와 window.location.href와의 차이점이 있는지?
-> myfeed/ProfileUpdatePopup.jsx에도 136라인에 Link 있음

### myfeed/Profile.jsx
- [x] 44라인과 49라인의 차이?
49라인에서 {' '}는 잘못들어간건가?

### myfeed/ProfileUpdatePopup.jsx
- [ ] 64라인: 미현언니가 edit/UploadForm에서 getPhotoUrl()함수는 API에 작성한다고 했는데 여기에도 있음

**Comment by huiji0315** [comment]
## pages 폴더
### api/user.js
- [x] 33라인부터는 수정안할경우를 나타내는데
왜 getUserInfo로 받아서 json으로 보내주어야 하나요?

### api/feed/[feedUid].js
- [x] 43~48라인 : FeedList는 왜 !==이고 LikeFeeds는 === 인가?

### feed/index.js
- [x] fetch("/api/user")는 상대경로로도 가능하고 아래와 같이 localhost를 써줘도 되고 둘다 되는건가?
- [x] 40라인 : resultMessage 오타!!

### feed/[feedUid].js
- [x] 왜 여기에서만 getServerSideProps를 이용해서 http://localhost:3000 url을 사용하는지? 무슨 차이가 있는지?

### edit.js
- [x] 7~8라인 : const router = useRouter();
  	const { feedUid } = router.query; 설명 필요
	-> feed/index.js에도 나옴

### _app.js, _document.js
- [x] 교육 때 언급하는지?

**Comment by devmhl** [comment]
### pages/feed/[feedUid].js
- [x] **getServerSideProps** 함수 안에서 api routes 사용하지 말고 필요한 로직 직접 작성하라고함
---

[NextJs getServerSideProps 문서 ](https://nextjs.org/docs/basic-features/data-fetching#getserversideprops-server-side-rendering)

**Note**: You should not use [`fetch()`](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) to call an API route in `getServerSideProps`. Instead, directly import the logic used inside your API route. You may need to slightly refactor your code for this approach.

Fetching from an external API is fine!

**Comment by aeuna** [comment]
### Api
 1. const db = firebase.firestore()를 각 파일에서 계속 선언하고 있는데 firesotres에서 firebase.js에서 export const db= firebase.firestore() 이런식으로 쓰는건 어떤지
 
아래 링크와 같은 문제로 우리가 진행하는 방식으로 유지해야 할듯!
https://pekahblog.tistory.com/69?category=946813

**Comment by devmhl** [comment]
- [x] 상세화면 서버사이드렌더링으로 복구
- [x] 마이피드 사진그리드 spacing 이슈 해결
- [x] 좋아요 클릭 후 사용자 likeFeeds 업데이트 이슈 해결
