### ISSUE TITLE
[코드리뷰] 리뷰 피드백

### ISSUE THREAD

**Issue by devmhl** [aeuna/sullivan-SNS#56]
### edit/PhotoPreview.jsx
- [x] '사진을 업로드 하세요.' 글씨 크기를 줄여서 한줄에 보이도록 하는 것이 좋을듯

### edit/SubmitButton.jsx
- [x] 20라인 : router.push()와
feed/Feed.jsx 131라인 : window.location.href = `/feed/${uid}`; 의 차이가 뭔가요?
```
router.push() 사용으로 통일했어요

 window.location.href 방식을 사용하면 화면 전체가 새로고침 되어서 화면이동시 전체 화면이 깜빡이는 현상이 나타나는데
router.push 사용시 화면전체 새로고침 없이 자연스럽게 원하는 화면으로 이동할 수 있어요.
예를들면 window.location.href 사용하여 화면을 이동할 경우 화면 전체가 사라졌다가 새로운 화면이 나타나지만
router.push 사용시 상단바는 그대로 유지된 채로 아래 화면만 바뀜!
우리 앱 안에서의 라우팅 이동은 
```

### feed/Comment.jsx
- [x] 댓글 입력해서 send 버튼 누르면 댓글창에 올라가는데
댓글창을 닫았다가 다시 열거나 디테일 페이지에 가보거나 등을 하면
상태가 유지되지 않는 이유에 대해서 설명해주면 좋을듯
ex) 코드 상으로 setInputs하고 setComments했는데 왜 유지되지않는지?
```
교육에서 최소한의 기능만 다루고자 피드 데이터베이스에 댓글 정보까지 포함하지 않았음.
그래서 댓글을 입력하고 등록하는 기능만 간단하게 구현되었고, 피드 데이터베이스에 반영되진 않음.

상태 업데이트는 해당 화면에서 사용하는 상태 변수의 값을 바꿔줄 뿐
데이터베이스를 업데이트하는 로직은 작성되지 않았어요!
```

### feed/DetailFeed.jsx
- [x] 82~90라인 : 좋아하는 피드들 전체를 살펴보면서 feedid가 uid와 같으면
like 상태로 만들어주고 반복을 멈추는데 이 부분이 정확하게 무엇을 구현한건지 한번에 파악하기 힘듦
```
// 변경 전

useEffect(() => {
    let checkFeed = [];
    if (user.likeFeeds.length != 0) {
      setLikeFeeds(user.likeFeeds);
      checkFeed = [...user.likeFeeds];
    }
    for (const feedId of checkFeed) {
      if (uid === feedId) {
        setLiked({
          ...liked,
          status: true,
        });
        break;
      }
    }
  }, []);

```

```
// 변경 후 (변수명은 협의 후 바꿀 예정)

  useEffect(() => {
    if (user.likeFeeds.includes(uid)) {
      setLiked({
        status: true,
        num: like,
      });
    }
  }, []);
```
- [x] 93라인 : handleHeartClick() 함수 구현도 feedId와 uid를 비교해서 update하는 것 같은데 자세한 설명 부탁드립니다.
- [x] 151라인 : 실습 설명때 조건부렌더링연산자(&&) 설명해줘야할듯

### feed/Feed.jsx
- [x] 55~70라인 : 위에 언급한 feed/DetailFeed.jsx의 '82 ~ 90라인'과 비교하면서 설명해주면 좋을듯
- [x] fetch api 부분은 어디에서 어떤 방식으로 가져와서 뭘하려고 하는건지에 대해서도 자세한 설명을 해주면 좋을 것 같습니다.(개념 설명 필요)
다른 fetch들과 비교해가면서 설명해주면 이해가 더 쉬울 것 같음
- [x] Feed 컴포넌트 이름을 MainFeed로 하면 어떨지?

### layout/NotificationBar.jsx
- [x] 원래 Bar라고 하는지?
Header 컴포넌트 이름에 Bar의 느낌이 포함되어있어서
NotificationBar보다는 NotificiationMenu 등으로 바꾸면 어떨지?

### myfeed/PhtoGrid.jsx
- [x] 은아 말처럼 피드가 한줄로 붙어서 보임
그리고, 사진이 위아래로 늘려서 길쭉하게 보임(정상보다 세로로 늘린 느낌)

### myfeed/PhotoItem.jsx
- [x] 32라인 : Link href를 사용한거는 또 앞에서
router.push()와 window.location.href와의 차이점이 있는지?
-> myfeed/ProfileUpdatePopup.jsx에도 136라인에 Link 있음
```
jsx 태그 클릭 시 바로 화면 이동만 필요한 경우 next가 제공하는 <Link> 태그를 jsx 영역 안에 사용할 수 있음
근데 함수를 실행 후 화면이동이 필요할 땐 스크립트 영역 안에서 <Link>를 사용할 수 없고 대신 next/router를 사용할 수 있음.

이 next/link 와 next/router는 우리 앱 안에서 화면 깜빡임 없이 부드럽게 바뀌는 화면만 렌더링 해주는데
window.location.href는 화면 전체를 새로고침 하면서 이동하기 때문에 화면 전체가 사라졌다가 새로운 화면이 나타남.
우리가 외부 url로 이동하는 경우는 없기 때문에 next/link와 next/router로 통일함.

jsx 태그 안에서 바로 화면이동 url 넣어줄거다! => next/link
함수 호출 시 스크립트 안에서 화면이동이 필요하다! => next/router

- ProfileUpdatePopup 팝업에 있던 Link는 사용할 필요가 없어서 Typography로 수정함
```

### myfeed/Profile.jsx
- [x] 44라인과 49라인의 차이?
49라인에서 {' '}는 잘못들어간건가?
```
컴포넌트를 렌더링하는 영역에서는 공백을 인식하지 못해요
자바스크립트를 사용해서 띄어쓰기 표시를 해주기 위해 {} 괄호열고 ' ' 띄어쓰기 하나 넣어준거예요
```

### myfeed/ProfileUpdatePopup.jsx
- [ ] 64라인: 미현언니가 edit/UploadForm에서 getPhotoUrl()함수는 API에 작성한다고 했는데 여기에도 있음

### api/user.js
- [x] 33라인부터는 수정안할경우를 나타내는데
왜 getUserInfo로 받아서 json으로 보내주어야 하나요?

```
요청 메소드에 PATCH를 명시하지 않은 경우엔 기본적으로 GET 요청에 대한 응답을 반환하고있어요

그래서 해당 api로 GET 요청을 할 땐 
await fetch("/api/user"); 이렇게 url만 간단히 적어줘도 되고

수정을 위해 PATCH 요청을 할 땐
await fetch(`/api/feed/${feedUid}`, {
  method: "PATCH",
  body: JSON.stringify(updateParams),
  headers: {
    "Content-type": "application/json; charset=UTF-8",
  },
});
이렇게 요청 방법, 보내줄 데이터, 헤더를 적어줘야해요
```

### api/feed/[feedUid].js
- [x] 43~48라인 : FeedList는 왜 !==이고 LikeFeeds는 === 인가?

```
오타 수정  😢
```

### feed/index.js
- [x] fetch("/api/user")는 상대경로로도 가능하고 아래와 같이 localhost를 써줘도 되고 둘다 되는건가?
```
가능해요. nextjs에서는 fetch 사용시 호스트명을 생략해도 되는데
서버사이드 렌더링에서 사용할 땐 전체 호스트를 명시해줘야해서 
pages/feed/[feedUid].js 18라인 getServerSideProps 함수에서만 fetch 시 호스트명까지 붙여서 작성됐어요
```
- [x] 40라인 : resultMessage 오타!! 

### feed/[feedUid].js
- [x] 왜 여기에서만 getServerSideProps를 이용해서 http://localhost:3000 url을 사용하는지? 무슨 차이가 있는지?
```

```

### edit.js
- [x] 7~8라인 : const router = useRouter();
  	const { feedUid } = router.query; 설명 필요
	-> feed/index.js에도 나옴

### _app.js, _document.js
- [x] 교육 때 언급하는지? 
```
용도에 대해서만 간략하게 언급 예정
```

_Originally posted by @huiji0315 in https://github.com/aeuna/sullivan-SNS/issues/52#issuecomment-885117862_

**Comment by huiji0315** [comment]
### pages/api/user.js

- [x] 33라인부터는 수정안할경우를 나타내는데
왜 getUserInfo로 받아서 json으로 보내주어야 하나요?
1.
if (req.method === "PATCH") {
    const updateData = req.body;
    await updateUser(updateData);
    **return res.status(200).json({ message: "프로필이 수정되었습니다." });**
  }

2.
else {
    const userInfo = await getUserInfo();
    **return res.status(200).json(userInfo);**
  }

궁금했던 부분은 1번과 2번의 차이가 궁금해요!

2번의 경우에는 수정안할경우로 json에 userInfo만 넘겨주고
1번의 경우에는 수정할 경우로 json에 message 객체만 넘겨주는데
차이를 설명해주실 수 있나요?
@xianeml

**Comment by huiji0315** [comment]
[NextJs getServerSideProps 문서 ](https://nextjs.org/docs/basic-features/data-fetching#getserversideprops-server-side-rendering)

- [x] 위 문서를 읽어보니
_"You should use getServerSideProps only if you need to pre-render a page whose data must be fetched at request time."_
라고 하는데 왜 **pages/feed/[feedUid].js** 에서만 **서버사이드 렌더링**이 필요한가요?

이 부분 외에는
useEffect(() => {
    fetchData();
  }, []); 을 사용해서 **CSR**로 구현한걸로 이해하면 되나요?
아니면 더 놓친 부분이 있다면 설명 부탁드립니다!
@xianeml

**Comment by devmhl** [comment]
### components/edit/UploadForm.jsx
@aeuna 
 2. getPhotoUrl에서 이미지 미리보기 링크 구현할때, 사진을 바꿀때마다 파이어베이스 스토리지에 올리고 구현되는건 비효율적인것 같음! onChange 될때 파일객체랑 onloadend 사용하면 구현 가능. 간단하게 적어보면 let reader = new FileReader(); let file = e.target.files[0]; reader.onloadend = () => { … setSteate(file: file, previewUrl : reader.result } reader.readAsDataUrl(file); 요런식으로 찾아보면 스토리지에 올리지 않아도 previewUrl 통해 미리보기 구현 가능
 ```
기존코드를 아래와 같이 수정해서 확인해봤는데 PhotoPreview 영역에 이미지 불러오기는 잘 되지만
저장 버튼이 안눌리는 에러가 있음! 더 알아보는데 시간 걸릴 것 같아서 기존 코드 유지하기로
아래 코드로 한번 테스트 해주세요!

async function getPhotoUrl() {
    try {
      setLoading(true);
      const reader = new FileReader();
      const file = fileButton.current.files[0];
      reader.readAsDataURL(file);
      reader.onload = (e) => setPhotoUrl(e.target.result);
      setLoading(false);
    } catch (e) {
      console.error(e);
    }
  }
```

**Comment by aeuna** [comment]
7월27일 날짜로 생성된 게시글 uid가 제대로 생성되지 않은 것 같습니다! 확인해주세요!
![스크린샷 2021-07-28 오전 12 43 15](https://user-images.githubusercontent.com/42725903/127189284-c2d78cee-0289-4914-961d-90fea0766eb2.png)

**Comment by devmhl** [comment]
> [NextJs getServerSideProps 문서 ](https://nextjs.org/docs/basic-features/data-fetching#getserversideprops-server-side-rendering)
> 
> * [x]  위 문서를 읽어보니
>   _"You should use getServerSideProps only if you need to pre-render a page whose data must be fetched at request time."_
>   라고 하는데 왜 **pages/feed/[feedUid].js** 에서만 **서버사이드 렌더링**이 필요한가요?
> 
> 이 부분 외에는
> useEffect(() => {
> fetchData();
> }, []); 을 사용해서 **CSR**로 구현한걸로 이해하면 되나요?
> 아니면 더 놓친 부분이 있다면 설명 부탁드립니다!
> @xianeml

마쟈용 [feedUid].js에서만 서버사이드렌더링 구현했습니다!
나머지는 클라이언트 사이드에서 데이터를 가져와서 렌더링한 CSR이에요

**Comment by devmhl** [comment]
> ### pages/api/user.js
> * [x]  33라인부터는 수정안할경우를 나타내는데
>   왜 getUserInfo로 받아서 json으로 보내주어야 하나요?
> 
> 
> if (req.method === "PATCH") {
> const updateData = req.body;
> await updateUser(updateData);
> **return res.status(200).json({ message: "프로필이 수정되었습니다." });**
> }
> 
> 
> else {
> const userInfo = await getUserInfo();
> **return res.status(200).json(userInfo);**
> }
> 
> 궁금했던 부분은 1번과 2번의 차이가 궁금해요!
> 
> 2번의 경우에는 수정안할경우로 json에 userInfo만 넘겨주고
> 1번의 경우에는 수정할 경우로 json에 message 객체만 넘겨주는데
> 차이를 설명해주실 수 있나요?
> @xianeml

## 피드백
`/api/user`는 사용자 정보를 조회하고 수정할 수 있는 API 입니다.
두 가지 동작을 갖고있기 때문에 `pages/api/user.js`파일을 보면 제일 하단에서 handler 함수가
이 API로 들어온 요청방법이 단순 조회인지(2번코드), 수정을 위한건지(1번코드)를 구분해서  
getUserInfo 또는 updateUser 함수에게 DB 처리를 맡기고 있어요.

### /api/user로 사용자 정보 조회하기
```
await fetch("/api/user");
```
 위와 같이 GET 방식으로 단순히 사용자 정보를 받아오기 위해 클라이언트에서 API를 호출할 경우  
서버는 2번 코드처럼 사용자 정보가 담긴 객체를 리턴해줍니다.
우리 목적이 사용자 정보 조회였기 때문에 이렇게 리턴받은 사용자 정보 객체를 고대로 사용하면 됩니다.

### /api/user로 사용자 정보 수정하기
```
await fetch(`/api/user`, {
        method: "PATCH",
        body: JSON.stringify(updateData),
        headers: {
          "Content-type": "application/json; charset=UTF-8",
        },
      });

```
하지만 사용자 정보를 수정하기 위해 클라이언트에서 이 API를 사용할 경우  
fetch 함수 두번째 인자에 옵션이 붙어서 저렇게 길어져요.
이번에는 메소드까지 PATCH 라고 명시를 해주고 body에 업뎃할 데이터도 넘겨줬어요. 수정해달라고!
수정 완료 후에 { message: "프로필이 수정되었습니다." } 이렇게 메시지를 리턴하는데요  
이 메시지를 받아오면 사용자 정보 수정 후에 Snackbar 알림창에 '수정되었습니다' 하고 띄워줄 수 있어요
