### ISSUE TITLE
[로그인] firebase auth 구현

### ISSUE THREAD

**Issue by devmhl** [aeuna/sullivan-SNS#7]
### 작업내용
- 파이어베이스 auth 사용하여 로그인기능 구현
- 소셜로그인 기능 사용
- 로그인 후 메인화면으로 이동
- 상단바에 로그인 된 사용자 정보 표시

**Comment by devmhl** [comment]
### 리뷰
1. 로그인 사용자 토큰 저장 후 로그인 시 사용자 검사 필요해요~
![image](https://user-images.githubusercontent.com/67747870/121770621-4ace2b80-cba5-11eb-8b3f-e497bd41cff5.png)
2. 로그인 세션 길게 유지해주세요~

**Comment by huiji0315** [comment]
### 21.06.13 리뷰

- 로그인 후 메인화면으로 이동 
-> 로그인 후 메인페이지로 이동하지 않고, 빈페이지로 남아있음
- 상단바에 로그인 된 사용자 정보 표시
-> 빈페이지 상태에서 우측 상단의 사용자 정보를 클릭하면 마이피드 페이지로 잘 넘어옴

+)
- 로그인 페이지로 들어가서 로그인하고, + 버튼을 통해 edit 페이지로 들어갈 수 있음
- 마이피드 페이지도 로그인해야 들어갈 수 있음(에러 발생)
- 마이피드 페이지에서 메인으로 돌아오기위해 좌측 상단의 Sullivan-SNS를 누르면, 로그인 상태가 풀려 에러가 발생함

**Comment by kelee98** [comment]
1.세션 유지 자동 로그인 구현
그런데도 처음에 rebuilding 될때는 로그인 끊김...

**Comment by kelee98** [comment]
자동 로그인 때문에 로그아웃 기능 구현 
로그아웃 버튼은 알람표시 아래에 위치해 있음
로그아웃 시 메인 페이지로 이동
