### ISSUE TITLE
[생성화면] 게시물 생성 및 수정화면 구현

### ISSUE THREAD

**Issue by devmhl** [aeuna/sullivan-SNS#8]
### 화면 구성
- 생성/수정화면 같이 사용
- 사진 첨부 후 사진 미리보기 확인
- 위치 추가 및 사람태그는 null 가능
- 이전버튼: 클릭시 메인화면 이동
- 공유 클릭 후  알림창 띄운 뒤 새 게시물 업로드된 메인화면 이동

**Comment by devmhl** [comment]
1. 오늘 계획했던 일정
- 경은이 edit2 api 코드 참고하여 생성/수정 api 만들기
2. 실제 작업한 내용
- edit 화면 폼 submit 형태로 코드 수정
- 돔 선택시 useRef 사용
- 업로드 api 작성
3. 딜레이된 부분
- 업로드 api 완성
4. 피드백 받은 코드리뷰 반영 여부
아직 피드백 없음
5. 내일 작업 계획
- upload api 완성하기
- 이미지 미리보기 구현

**Comment by devmhl** [comment]
### 완료
- 게시물 업로드 함수 작성
- 테스트피드 컬렉션에 테스트 완료
- 이미지 미리보기 구현

### 할 일
- 피드 컬렉션으로 업로드 테스트
- 생성 / 수정 모드 분리
- 게시물 수정 화면 구성
- 수정 api 테스트

**Comment by huiji0315** [comment]
### 21.06.13 리뷰

- 메인페이지에서 언급한 문제와 동일하게, 게시글 업로드 시에 사진을 올리지 않아도 사진과 같은 크기로 빈 상자가 올라오는 문제를 해결하기 위해서 함께 고민이 필요할 것으로 생각됨
- 목록 버튼 기능 구현 아직 안됨
- 글 수정하기 부분은 디테일 페이지에서 수정버튼 누르면 갈 수 있게 구현할 예정

**Comment by aeuna** [comment]
- 게시글 업로드시에 사진을 올리지 않아도 글만 뜰수있도록 변경완료!
